language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
branches:
  only:
  - master
before_install:
- pip install -U pip
install:
- pip install coveralls
- pip install -e .[test]
script:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then py.test -v; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then py.test -v -m "not scihub"; fi'
- coverage run --source=sentinelsat -m py.test
after_success:
  - coveralls
sudo: false
notifications:
  email: false
