language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
branches:
  only:
  - master
before_install:
- pip install -U pip
install:
- pip install coveralls
- pip install -e .[test]
script:
- py.test -v
- coverage run --source=sentinelsat -m py.test
after_success:
  - coveralls
sudo: false
notifications:
  email: false
